### ISSUE TITLE
Scope out structure of format with example notebook and document

### ISSUE THREAD

**Issue by hmacdope** [Becksteinlab/zarrtraj#1]
## Is your feature request related to a problem? ##

We need to decide what the basic format for the trajectory will look like. Like the H5MD trajectory (uses and HDF5 group) the zarr trajectory format will likely take the form of a zarr group: https://zarr.readthedocs.io/en/stable/api/hierarchy.html that contains the three arrays (coordinates, velocities, forces).  https://zarr.readthedocs.io/en/stable/tutorial.html#groups will be helpful here.

## Describe the solution you'd like ##

Come up with an example jupyter notebook where you read some random data (say 1000 particles worth) into a zarr group containing the three arrays. 

Play around with the API and see what feels natural, try and load and save from disk. 

A key questions, how big is the resulting zarr object? How will this scale with particle size? Can you compare with other formats?

Once you have done this you can make this into a document that describes the conventions of the format you are adopting.

**Comment by orbeckst** [comment]
Create the file format as a document in the docs.

I'd suggest to have a separate document for each version of the format.
