### ISSUE TITLE
Write an MDAnalysis reader for your proposed format

### ISSUE THREAD

**Issue by hmacdope** [Becksteinlab/zarrtraj#2]
## Is your feature request related to a problem? ##

Once #1 is addressed you can begin writing an MDAnalysis Reader class (subclasses ReaderBase) for the prototype zarr files you have created.  

You can use this PR that added the TNG as a rough guide as to how MDAnalysis readers work: https://github.com/MDAnalysis/mdanalysis/pull/3765/files . Don't worry about all the MDA stuff just focus on TNGReader

You will need to also write some tests and build out your testing infrastructure.

**Comment by orbeckst** [comment]
@ljwoods2 is this completed?

**Comment by orbeckst** [comment]
In your docs, include information on how to enable caching for reads from cloud storage.

Document limitations (e.g., is random access possible?).
