### ISSUE TITLE
Benchmark your format in its raw form

### ISSUE THREAD

**Issue by hmacdope** [Becksteinlab/zarrtraj#3]
We need to understand the raw performance of zarr itself in terms of speed and memory.  You should investigate this using a somewhat decent computer (ask @orbeckst)

How long does it take to read and write to the trajectory format?

How does it scale with respect to system size? (I would focus on mainly just a group containing positions)

How does compression of the zarr array play a role in this? https://zarr.readthedocs.io/en/stable/tutorial.html#compressors. Blosc is used by default, but how does the CLEVEL argument change things?

 Do we see the typical tradeoffs between speed and size (https://www.ibm.com/docs/en/linux-on-z?topic=wysk-compression-speed-3).

**Comment by hmacdope** [comment]
I should note that we are not looking to do a comprehensive benchmarking analysis here, just to get some ballpark figures so we can compare.

**Comment by orbeckst** [comment]
I suggest to add benchmarking data to the docs, then we have them already in one place.

When you make figures, store *both* a PNG version (for the docs) and an editable PDF version next to it (for papers etc). It _might_ also work to just write a SVG — see if sphinx likes that.
