### ISSUE TITLE
Fix specification to link to the H5MD format and make clear that a zarrtraj file is a re-skin of H5MD 

### ISSUE THREAD

**Issue by hmacdope** [Becksteinlab/zarrtraj#47]
* Fix specification to link to the H5MD format
*  make clear that a zarrtraj file is a re-skin of H5MD 
* Make an example that used an H5MD file from remote

**Comment by ljwoods2** [comment]
Merged some docs changes that include this info, not sure what I have to do get them to build. Will make sure it gets built
