### ISSUE TITLE
Register as an MDAKit

### ISSUE THREAD

**Issue by hmacdope** [Becksteinlab/zarrtraj#56]
Do we want to register this as an [MDAKit](https://github.com/MDAnalysis/MDAKits?tab=readme-ov-file)? 

CC @orbeckst

**Comment by orbeckst** [comment]
Good idea. It's definitely in scope.

**Comment by ljwoods2** [comment]
Closing because Zarrtraj was registered in MDAnalysis/MDAKits#157
