### ISSUE TITLE
add CITATION.cff file

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/zarrtraj#69]
Add a [CITATION.cff](https://citation-file-format.github.io/) file with
- title
- authors
- affiliations

so that the Zenodo archive contains the same metadata as the JOSS paper #68 .

**Comment by orbeckst** [comment]
Potentially helpful information when I did this recently
- https://github.com/alchemistry/alchemlyb/issues/394
- https://github.com/alchemistry/alchemlyb/pull/395

**Comment by ljwoods2** [comment]
Closed by #68
